# SOURCE: http://code.google.com/p/starworld/source/browse/trunk/Depend/MyGUI/CMake/Packages/FindCINDER.cmake?r=257

set(CINDER_ROOT "" CACHE PATH "Path to Cinder sources")
SET(CINDER_FOUND FALSE)
IF(EXISTS ${CINDER_ROOT}/include AND EXISTS ${CINDER_ROOT}/lib)
  SET(CINDER_INCLUDE_DIRS ${CINDER_ROOT}/include ${CINDER_ROOT}/boost)
  SET(CINDER_LIBRARY_DIRS ${CINDER_ROOT}/lib)
ENDIF()
IF(CINDER_INCLUDE_DIRS AND CINDER_LIBRARY_DIRS)
  IF(WIN32)  # Windows
    FIND_LIBRARY(CINDER_DEBUG_LIBRARY   NAMES CINDER_d
                 PATH_SUFFIXES "" Debug   PATHS ${CINDER_LIBRARY_DIRS} NO_DEFAULT_PATH)
    FIND_LIBRARY(CINDER_RELEASE_LIBRARY NAMES CINDER
                 PATH_SUFFIXES "" Release PATHS ${CINDER_LIBRARY_DIRS} NO_DEFAULT_PATH)
    SET(CINDER_LIBRARIES)
    IF(CINDER_DEBUG_LIBRARY AND CINDER_RELEASE_LIBRARY)
      SET(CINDER_LIBRARIES debug ${CINDER_DEBUG_LIBRARY} optimized ${CINDER_RELEASE_LIBRARY})
    ELSEIF(CINDER_DEBUG_LIBRARY)
      SET(CINDER_LIBRARIES ${CINDER_DEBUG_LIBRARY})
    ELSEIF(CINDER_RELEASE_LIBRARY)
      SET(CINDER_LIBRARIES ${CINDER_RELEASE_LIBRARY})
    ENDIF(CINDER_DEBUG_LIBRARY AND CINDER_RELEASE_LIBRARY)
  ELSE(WIN32)  # Linux etc
    FIND_LIBRARY(CINDER_LIBRARIES NAMES cinder PATHS ${CINDER_LIBRARY_DIRS} NO_DEFAULT_PATH)
  ENDIF(WIN32)
  IF(CINDER_LIBRARIES)
    SET(CINDER_FOUND TRUE)
  ENDIF()
ENDIF()
IF(CINDER_FOUND)
  MESSAGE(STATUS "Found CINDER: headers at ${CINDER_INCLUDE_DIRS}, libraries at ${CINDER_LIBRARIES}")
ENDIF(CINDER_FOUND)
